language: ruby
rvm:
  - 2.1.5
script:
  - bundle exec rubocop
 notifications:
  slack:
    rooms:
      - devops-yhe5868:UPNr6s35o54WJ5bXncN2Vk7r#general
      - devops-yhe5868:UPNr6s35o54WJ5bXncN2Vk7r#random
      - devops-yhe5868:UPNr6s35o54WJ5bXncN2Vk7r#test-buldozer83a
